### ISSUE TITLE
When text is too long, footer is beyond screen

### ISSUE THREAD

**Issue by monntecc** [monntecc/lunaeditor#5]
**Describe the bug**
When you are making a text, and you make it too long, then footer is scrollable in X axis

**To Reproduce**
1. Create/open file
2. Write something long in editor (must be in 1 line)
3. look at the footer

**Expected behavior**
Right side of the footer will stay in place

**Screenshots**
![image](https://github.com/monntecc/lunaeditor/assets/92087357/149881e7-c3b9-4de6-bb7f-da31f5d06983)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Version Luna first release

**Additional context**
Use readme.md to see it

**Comment by Yix0n** [comment]
still happening when window isn't big (width)

Wrong version, but found other issue
